# spring
spring:
  profiles: dev

  # redis
  redis:
    host: 'www.pingssys.com'
    password: 'Zhou1182969'
    port: 32000
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数(负值表示没有限制)
        max-active: 8
        # 连接池最大阻塞等待时间(负值表示没有限制)
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

# Dubbo
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: cn.pings.web.bill

  # ApplicationConfig Bean
  application:
   id: pings-web-bill-dev
   name: pings-web-bill-dev
   qos-host: 33333

  # RegistryConfig Bean
  registry:
    id: client-bill
    address: zookeeper://www.pingssys.com:32568
  metadata-report:
    address: zookeeper://www.pingssys.com:32568
  config-center:
    address: zookeeper://www.pingssys.com:32568

# 系统管理 config
sys:
  # Service version
  service:
    version: 0.0.1
  jwt:
    secret: ==SFddfenfV2FuZzkyNjQ1NGRTQkFQSUpXVA==
     # 访问令牌过期时长(分钟)，默认配置5分钟
    access-token:
      expire-time: 10
    # 刷新令牌过期时长(分钟)，默认配置60分钟
    refresh-token:
      expire-time: 60

# 账单管理 config
bill:
  # Service version
  service:
    version: 0.0.1

# 服务器配置
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

---

# spring
spring:
  profiles: prod

  # redis
  redis:
    host: '10.254.235.117'
    password: 'Zhou1182969'
    port: 6379
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数(负值表示没有限制)
        max-active: 8
        # 连接池最大阻塞等待时间(负值表示没有限制)
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

# Dubbo
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: cn.pings.web.bill

  # ApplicationConfig Bean
  application:
   id: pings-web-bill
   name: pings-web-bill

  # RegistryConfig Bean
  registry:
    id: client-bill
    address: zookeeper://10.254.242.130:2181
  metadata-report:
    address: zookeeper://10.254.242.130:2181
  config-center:
    address: zookeeper://10.254.242.130:2181

# 系统管理 config
sys:
  # Service version
  service:
    version: 1.0.0
  jwt:
    secret: ==SFddfenfV2FuZzkyNjQ1NGRTQkFQSUpXVA==
     # 访问令牌过期时长(分钟)，默认配置5分钟
    access-token:
      expire-time: 5
    # 刷新令牌过期时长(分钟)，默认配置60分钟
    refresh-token:
      expire-time: 20

# 账单管理 config
bill:
  # Service version
  service:
    version: 1.0.0