apiVersion: v1
kind: Service          #表示Kubernetes Service
metadata:
  name: redis          #Service的名称
spec:
  type: NodePort
  ports:
    - port: 6379       #Service提供服务的端口号
      nodePort: 32000  #Service提供对外服务的端口号
  selector:
    app: redis         #Service对应的Pod的标签